export const mockDashboardSummary = {
  totalFoods: 52,
  totalAttractions: 34,
  totalVendors: 28,
  totalStories: 47,
  totalExplorers: 12400,
};

export const mockRecommended = [
  {
    id: "1",
    title: "Kashi Vishwanath Temple",
    type: "Temple",
    rating: 4.9,
    subtitle: "The holiest Shiva temple in the universe",
    imageUrl: "/images/kashi-vishwanath.png",
    location: "Vishwanath Gali, Varanasi",
  },
  {
    id: "2",
    title: "Banarasi Kachori Sabji",
    type: "Food",
    rating: 4.8,
    subtitle: "Crispy kachori dipped in spiced sabji",
    imageUrl: "/images/kachori-sabji.png",
    location: "Godowlia Chowk",
  },
  {
    id: "3",
    title: "Ganga Aarti at Dashashwamedh",
    type: "Event",
    rating: 5.0,
    subtitle: "A divine spectacle every evening at dusk",
    imageUrl: "/images/ganga-aarti.png",
    location: "Dashashwamedh Ghat",
  },
  {
    id: "4",
    title: "Malaiyoo — Winter Delight",
    type: "Food",
    rating: 4.7,
    subtitle: "Feather-light sweetened cream, winter only",
    imageUrl: "/images/malaiyoo.png",
    location: "Chowk, Varanasi",
  },
  {
    id: "5",
    title: "Ghats at Night",
    type: "Experience",
    rating: 4.9,
    subtitle: "The ghats transform after sunset",
    imageUrl: "/images/ghats-night.png",
    location: "Manikarnika Ghat",
  },
  {
    id: "namo-ghat-rec",
    title: "Namo Ghat",
    type: "Ghat",
    rating: 4.8,
    subtitle: "Modern riverfront ghat famous for folded-hands sculptures",
    imageUrl: "/images/Namo Ghat.png",
    location: "Rajghat, Varanasi",
  },
];

export const mockCategories = [
  { id: "1", name: "Authentic Food", type: "food", count: 52 },
  { id: "2", name: "Sacred Temples", type: "temple", count: 34 },
  { id: "3", name: "Holy Ghats", type: "ghat", count: 18 },
  { id: "4", name: "Heritage Sites", type: "heritage", count: 22 },
  { id: "5", name: "Timeless Stories", type: "story", count: 47 },
  { id: "6", name: "Arts & Crafts", type: "craft", count: 15 },
];

export const mockVendors = [
  {
    id: "1",
    name: "Deena Chat Bhandar",
    nameHindi: "दीना चाट भण्डार",
    category: "Chaat & Street Food",
    specialty: "Legendary Tamatar Chaat & Dahi Vada in earthen kulhads",
    location: "Dashashwamedh Road / Luxa",
    rating: 4.9,
    reviewsCount: "4.2k+",
    priceRange: "₹40 - ₹120",
    timing: "02:00 PM - 10:30 PM",
    imageUrl: "/images/vendors/deena-chat-bhandar.jpg",
    isVerified: true,
  },
  {
    id: "2",
    name: "Ksheer Sagar",
    nameHindi: "क्षीर सागर",
    category: "Sweets & Dairy",
    specialty: "Royal Banarasi Lal Peda, Winter Malaiyyo & Chena Sweets",
    location: "Godowlia / Sigra Crossing",
    rating: 4.8,
    reviewsCount: "3.8k+",
    priceRange: "₹60 - ₹450",
    timing: "07:00 AM - 11:00 PM",
    imageUrl: "/images/vendors/ksheer-sagar.jpg",
    isVerified: true,
  },
  {
    id: "3",
    name: "Vandana Silks",
    nameHindi: "वंदना सिल्क्स",
    category: "Banarasi Silk & Craft",
    specialty: "Pure Katan Silk Sarees, Bridal Jangla & Handloom Brocade",
    location: "Chowk Heritage Market",
    rating: 4.9,
    reviewsCount: "2.9k+",
    priceRange: "₹2,500 - ₹85,000",
    timing: "10:30 AM - 09:30 PM",
    imageUrl: "/images/vendors/vandana-silks.jpg",
    isVerified: true,
  },
  {
    id: "4",
    name: "Baati Chokha",
    nameHindi: "बेटियों का बाटी चोखा",
    category: "Authentic Dining",
    specialty: "Wood-Fired Desi Ghee Baati Chokha, Sattu Paratha & Kheer",
    location: "Anand Mandir Lane, Teliyabag",
    rating: 4.8,
    reviewsCount: "5.1k+",
    priceRange: "₹150 - ₹450",
    timing: "12:00 PM - 11:00 PM",
    imageUrl: "/images/vendors/baati-chokha.jpg",
    isVerified: true,
  },
  {
    id: "5",
    name: "Blue Lassi Shop",
    nameHindi: "ब्लू लस्सी शॉप (Estd. 1925)",
    category: "Lassi & Beverages",
    specialty: "Hand-Churned Fruit Rabdi Lassi in Terracotta Kulhads",
    location: "Kunj Gali, near Manikarnika Ghat",
    rating: 4.9,
    reviewsCount: "6.8k+",
    priceRange: "₹80 - ₹200",
    timing: "08:00 AM - 10:30 PM",
    imageUrl: "/images/vendors/blue-lassi-shop.jpg",
    isVerified: true,
  },
  {
    id: "6",
    name: "Kashi Chat Bhandar",
    nameHindi: "काशी चाट भण्डार (Since 1960)",
    category: "Chaat & Street Food",
    specialty: "Legendary Palak Patta Chaat, Tamatar Chaat & Gulab Jamun",
    location: "Godowlia Crossing, Main Market",
    rating: 4.9,
    reviewsCount: "7.4k+",
    priceRange: "₹50 - ₹150",
    timing: "03:00 PM - 11:00 PM",
    imageUrl: "/images/vendors/kashi-chat-bhandar.jpg",
    isVerified: true,
  },
  {
    id: "7",
    name: "The Ram Bhandar",
    nameHindi: "द राम भण्डार (Since 1960)",
    category: "Chaat & Street Food",
    specialty: "Parampara Se Aaj Tak — Heritage Morning Kachori Sabzi, Jalebi & Poori Sabzi",
    location: "Chowk, Thatheri Bazar",
    rating: 4.9,
    reviewsCount: "5.8k+",
    priceRange: "₹50 - ₹120",
    timing: "06:30 AM - 11:30 AM",
    imageUrl: "/images/vendors/ram-bhandar.jpg",
    isVerified: true,
  },
];

export const mockStories = [
  {
    id: "1",
    title: "The Legend of Kashi — Where Time Began",
    category: "Mythology",
    readTime: "8 min read",
    imageUrl: "/images/kashi-vishwanath.png",
    excerpt:
      "Varanasi is said to be as old as time itself. Lord Shiva chose this sacred land as his abode, and since then, the city has been a beacon for millions seeking moksha.",
  },
  {
    id: "2",
    title: "Banarasi Weaves — A Thread of Gold",
    category: "Culture",
    readTime: "6 min read",
    imageUrl: "/images/drone-view.png",
    excerpt:
      "For centuries, the weavers of Varanasi have crafted silk sarees that carry the city's soul in every thread. Each piece takes weeks, sometimes months, to complete.",
  },
  {
    id: "3",
    title: "The Ghats at Dawn — A Pilgrim's Journey",
    category: "Travel",
    readTime: "5 min read",
    imageUrl: "/images/evening-ghats.png",
    excerpt:
      "As the first light touches the Ganges, thousands of pilgrims descend the stone steps of the ghats. This ritual has continued unbroken for five thousand years.",
  },
  {
    id: "4",
    title: "Flavors of Kashi — A Culinary Heritage",
    category: "Food",
    readTime: "7 min read",
    imageUrl: "/images/kachori-sabji.png",
    excerpt:
      "From the crispy kachori to the ethereal malaiyoo, the food of Varanasi tells a story of tradition, spice, and an unrelenting love for life.",
  },
  {
    id: "5",
    title: "Ganga Aarti — The Fire That Never Dies",
    category: "Spirituality",
    readTime: "4 min read",
    imageUrl: "/images/ganga-aarti.png",
    excerpt:
      "Every evening at Dashashwamedh Ghat, the air fills with incense and chanting as priests perform the Ganga Aarti. It is not a ritual — it is a conversation with the divine.",
  },
];

export const mockEvents = [
  {
    id: "1",
    name: "Dev Deepawali",
    date: "Nov 15, 2025",
    location: "Dashashwamedh Ghat",
    description:
      "A million lamps illuminate the ghats as gods descend to bathe in the Ganga. The most spectacular sight in Varanasi.",
    imageUrl: "/images/ganga-aarti.png",
  },
  {
    id: "2",
    name: "Ganga Mahotsav",
    date: "Oct 30, 2025",
    location: "Assi Ghat",
    description:
      "Five-day festival celebrating the cultural heritage of Varanasi with music, art, and the sacred river.",
    imageUrl: "/images/evening-ghats.png",
  },
  {
    id: "3",
    name: "Kashi Vishwanath Corridor Festival",
    date: "Dec 13, 2025",
    location: "Vishwanath Temple",
    description:
      "Annual celebration marking the inauguration of the new temple corridor with special poojas and cultural programs.",
    imageUrl: "/images/kashi-vishwanath.png",
  },
  {
    id: "4",
    name: "Bundelkhandi Lok Festival",
    date: "Jan 14, 2026",
    location: "Ramnagar Fort",
    description:
      "A vibrant folk music and dance festival on the eastern banks of the Ganga showcasing regional cultural heritage.",
    imageUrl: "/images/drone-view.png",
  },
];

export const mockUserJourney = {
  level: 7,
  levelName: "Kashi Explorer",
  xp: 3420,
  xpToNext: 5000,
  placesExplored: 14,
  foodsTasted: 23,
  storiesRead: 31,
  eventsJoined: 5,
};

export const mockAiSuggestions = [
  { id: "1", text: "Best ghats to visit at sunrise?" },
  { id: "2", text: "Where to eat authentic kachori?" },
  { id: "3", text: "What is the history of Kashi Vishwanath?" },
  { id: "4", text: "Plan a 3-day itinerary for Varanasi" },
  { id: "5", text: "Tell me about the Ganga Aarti" },
];

export const mockWishlist = [
  {
    id: "attr_1",
    title: "Kashi Vishwanath Temple",
    itemType: "Attraction",
    imageUrl: "/images/kashi-vishwanath-aerial.jpg",
  },
  {
    id: "food_1",
    title: "Tamatar Chaat",
    itemType: "Food",
    imageUrl: "/images/tamatar-chaat.png",
  },
  {
    id: "vendor_1",
    title: "Deena Chat Bhandar",
    itemType: "Vendor",
    imageUrl: "/images/vendors/deena-chat-bhandar.jpg",
  },
  {
    id: "vendor_5",
    title: "Blue Lassi Shop",
    itemType: "Vendor",
    imageUrl: "/images/vendors/blue-lassi-shop.jpg",
  },
  {
    id: "vendor_6",
    title: "Kashi Chat Bhandar",
    itemType: "Vendor",
    imageUrl: "/images/vendors/kashi-chat-bhandar.jpg",
  },
  {
    id: "vendor_7",
    title: "The Ram Bhandar",
    itemType: "Vendor",
    imageUrl: "/images/vendors/ram-bhandar.jpg",
  },
  {
    id: "attr_3",
    title: "Assi Ghat",
    itemType: "Attraction",
    imageUrl: "/images/assi-ghat-aarti.jpg",
  },
];
