export interface HistoryStory {
  title: string;
  subtitleEn: string;
  subtitleHi: string;
  image: string;
  english: string;
  hindi: string;
  
  // Premium details attributes
  type?: "Temple" | "Ghat" | "Food" | "Boat" | "Heritage";
  architecture?: string;
  timings?: string;
  bestTimeEn?: string;
  dressCode?: string;
  photoRules?: string;
  prasadInfo?: string;
  nearbySpots?: string[];
  ingredients?: string[];
  spiceLevel?: number; // 1 to 5
  sweetnessLevel?: number; // 1 to 5
  vegOption?: string;
  bestVendors?: string[];
  calories?: string;
  priceRange?: string;
  popularityData?: number[];
}

export const STORIES_DATA: Record<string, HistoryStory> = {
  "Kashi Vishwanath Temple": {
    title: "Kashi Vishwanath Temple",
    subtitleEn: "Spiritual Icon of Lord Shiva",
    subtitleHi: "भगवान शिव का आध्यात्मिक प्रतीक",
    image: "/images/kashi-vishwanath-aerial.jpg",
    english: "According to Hindu scriptures, Kashi Vishwanath is the heart of Varanasi, a place created directly by Lord Shiva and Goddess Parvati at the dawn of creation. The temple houses one of the twelve sacred Jyotirlingas, representing the infinite pillar of light of Shiva. Historically, the temple's legacy is a story of incredible resilience. The original ancient structure was destroyed by Qutb-ud-din Aibak's army in 1194 CE, rebuilt by local devotees, and demolished again under subsequent rulers. In 1669 CE, Emperor Aurangzeb destroyed the temple to build the Gyanvapi Mosque, whose walls still carry the architecture of the original temple. In 1780 CE, Maharani Ahilyabai Holkar of Indore built the current temple adjacent to the mosque. Maharaja Ranjit Singh of Punjab donated 1,000 kg of pure gold to plate the temple domes in 1835. In December 2021, the Kashi Vishwanath Corridor was inaugurated by Prime Minister Narendra Modi, directly linking the temple to the holy Ganges River, opening a grand pathway for millions of devotees to walk from the river directly to the deity.",
    hindi: "पौराणिक आख्यानों के अनुसार, काशी विश्वनाथ मंदिर सृष्टि की उत्पत्ति के समय स्वयं भगवान शिव और माता पार्वती द्वारा स्थापित किया गया था। यह मंदिर भगवान शिव के बारह ज्योतिर्लिंगों में से एक है, जो शिव के अनंत प्रकाश स्तंभ को दर्शाता है। इतिहास में, इस मंदिर की कहानी अत्यंत संघर्षपूर्ण और लचीली रही है। 1194 ईस्वी में कुतुबुद्दीन ऐबक की सेना ने प्राचीन मूल मंदिर को ध्वस्त कर दिया था, जिसे भक्तों ने पुनः स्थापित किया। इसके बाद 1669 ईस्वी में मुगल शासक औरंगजेब ने इसे तोड़कर ज्ञानवापी मस्जिद का निर्माण कराया, जिसकी दीवारों पर आज भी मूल मंदिर की वास्तुकला देखी जा सकती है। वर्तमान मंदिर का निर्माण 1780 में इंदौर की रानी महारानी अहिल्याबाई होल्कर ने मस्जिद के ठीक बगल में कराया था। इसके बाद 1835 में पंजाब के महाराजा रणजीत सिंह ने मंदिर के गुंबदों को सोने से मढ़ने के लिए 1000 किलोग्राम शुद्ध सोना दान किया था। दिसंबर 2021 में, प्रधानमंत्री नरेंद्र मोदी द्वारा काशी विश्वनाथ कॉरिडोर का उद्घाटन किया गया, जिसने मंदिर को सीधे पवित्र गंगा नदी से जोड़ दिया, जिससे श्रद्धालुओं के लिए नदी से सीधे गर्गृह तक जाने का मार्ग सुगम हो गया।",
    type: "Temple",
    architecture: "Nagara-style architecture featuring three gold-plated domes and a majestic main sanctorum built using pink sandstone and white marbles.",
    timings: "04:00 AM - 11:00 PM",
    bestTimeEn: "During Mangala Aarti (3:00 AM) or late evening (8:00 PM onwards) for lower queues.",
    dressCode: "Traditional Indian attire is recommended. Saree for women and Dhoti/Kurta for men during special rituals.",
    photoRules: "Photography is strictly prohibited inside the inner temple complex. Lockers are available.",
    prasadInfo: "Special Besan Laddoos, dry fruits, and Gangajal offerings distributed outside the main exit gates.",
    nearbySpots: ["Dashashwamedh Ghat", "Ganga Dwar", "Blue Lassi Shop"],
    bestVendors: ["Government Trust Ticket counter", "VIP Helpdesk inside the Corridor portal"]
  },
  "Assi Ghat": {
    title: "Assi Ghat",
    subtitleEn: "Peaceful riverside ghat for yoga & spirituality",
    subtitleHi: "योग और आध्यात्मिकता के लिए शांत नदी तट",
    image: "/images/assi-ghat-aarti.jpg",
    english: "Assi Ghat is situated at the sacred confluence of the Ganga and Assi rivers, marking the southern boundary of Varanasi. According to the Agni Purana and Matsya Purana, Goddess Durga, after defeating the demons Shumbha and Nishumbha, threw her sword away. The sword struck the ground, creating a stream that became the Assi River. Bathing here during the auspicious month of Kartik is believed to wash away all earthly sins. Historically, Tulsidas, the legendary poet who wrote the Ramcharitmanas, lived at Assi Ghat and breathed his last here in 1623 CE. Today, Assi Ghat has transitioned into a prominent cultural hub, famous for 'Subah-e-Banaras' - a magnificent daily morning initiative starting before dawn. Devotees and travellers gather to witness a beautiful morning Ganga Aarti, listen to Vedic mantras chanted by young priests, practice mass yoga sessions on the steps, and enjoy soulful Indian classical music concerts as the sun rises over the river.",
    hindi: "अस्सी घाट गंगा और अस्सी नदियों के पावन संगम पर स्थित है, जो वाराणसी की दक्षिणी सीमा को निर्धारित करता है। अग्नि पुराण और मत्स्य पुराण के अनुसार, महिषासुर और शुंभ-निशुंभ दैत्यों का वध करने के बाद जब देवी दुर्गा ने क्रोध में अपनी तलवार फेंकी, तो वह धरती पर गिरी और वहां से अस्सी नदी की धारा निकली। कार्तिक मास के दौरान यहां स्नान करने का अत्यधिक आध्यात्मिक महत्व है। महान संत और रामचरितमानस के रचयिता गोस्वामी तुलसीदास जी ने इसी घाट पर जीवन के अंतिम वर्ष बिताए थे और 1623 ईस्वी में यहीं महासमाधि ली थी। वर्तमान में, अस्सी घाट 'सुबह-ए-बनारस' के लिए दुनिया भर में प्रसिद्ध है, जहां भोर में गंगा आरती, वेदमंत्रों का पाठ, सामूहिक योग और शास्त्रीय संगीत की प्रस्तुति के साथ बनारस की सुबह का स्वागत किया जाता है।",
    type: "Ghat",
    architecture: "Wide semi-circular stone steps rising from the riverbed with dedicated performance platforms.",
    timings: "Open 24 hours (Morning event starts at 05:00 AM)",
    bestTimeEn: "05:00 AM - 07:30 AM for the Subah-e-Banaras spiritual morning routine.",
    dressCode: "Modest comfortable clothes suitable for sitting on steps and yoga activities.",
    photoRules: "Photography is allowed everywhere. Be respectful of pilgrims bathing.",
    prasadInfo: "Warm cardamom tea and local sweets available at near-front heritage stalls.",
    nearbySpots: ["Ravidas Ghat Jetty", "Pappu Chai Shop"],
    bestVendors: ["Subah-e-Banaras Trust office at Assi steps"]
  },
  "Sarnath": {
    title: "Sarnath",
    subtitleEn: "Where Buddha gave his first sermon",
    subtitleHi: "जहाँ बुद्ध ने अपना पहला उपदेश दिया था",
    image: "/images/sarnath.png",
    english: "Located 10 km from Varanasi, Sarnath is the cradle of Buddhism. In the 6th century BCE, after achieving Supreme Enlightenment under the Bodhi tree in Bodh Gaya, Gautama Buddha traveled to Sarnath. Here, in the quiet Deer Park (Isipatana), he met his five former companions and delivered his first sermon, known as the 'Dhammacakkappavattana Sutta' (Turning of the Wheel of Law). Sarnath is also where the Buddhist Sangha was born. In the 3rd century BCE, Emperor Ashoka built several structures here, including the 143-foot-tall Dhamek Stupa and the monolithic Ashoka Pillar. The spectacular Lion Capital of Ashoka, recovered from the ruins of Sarnath, is now the National Emblem of India, and the Wheel of Dharma (Dharmachakra) is featured in the center of the Indian national flag. Sarnath is also sacred to Jains as the birthplace of Shreyansanatha, the eleventh Jain Tirthankara.",
    hindi: "वाराणसी से केवल 10 किलोमीटर की दूरी पर स्थित सारनाथ बौद्ध धर्म का जन्मस्थान माना जाता है। छठी शताब्दी ईसा पूर्व में, बोधगया में बोधि वृक्ष के नीचे परम ज्ञान प्राप्त करने के बाद, महात्मा बुद्ध सारनाथ के मृगदाव (हिरण पार्क) पहुंचे थे। यहाँ उन्होंने अपने पांच शिष्यों को अपना पहला उपदेश दिया, जिसे बौद्ध परंपरा में 'धर्मचक्रप्रवर्तन सूत' (कानून के पहिये का घूमना) कहा जाता है। सम्राट अशोक ने तीसरी शताब्दी ईसा पूर्व में इस स्थल पर कई मठों और स्तूपों का निर्माण कराया, जिसमें धमेख स्तूप प्रमुख है। सारनाथ के अवशेषों से प्राप्त अशोक स्तंभ का सिंह शीर्ष भारत का राष्ट्रीय प्रतीक है और इसके निचले भाग का चक्र हमारे राष्ट्रीय ध्वज के केंद्र में सुशोभित है। सारनाथ जैन धर्म के अनुयायियों के लिए भी पवित्र है, क्योंकि यह ग्यारहवें तीर्थंकर श्रेयांसनाथ का जन्मस्थान है।",
    type: "Heritage",
    architecture: "Ancient brick stupas, carved Ashokan columns, and beautifully preserved Buddhist ruins dating from 3rd century BCE.",
    timings: "06:00 AM - 06:00 PM",
    bestTimeEn: "Cool winter mornings (November to February) or early evenings.",
    dressCode: "Casual modest attire. Shoes must be removed before stepping inside active temples.",
    photoRules: "Allowed. Professional video cameras require archaeological permissions.",
    prasadInfo: "Sacred thread and flowers at local Thai & Japanese Buddhist shrines nearby.",
    nearbySpots: ["Chaukhandi Stupa", "Sarnath Archaeological Museum"],
    bestVendors: ["Archaeological Survey of India (ASI) ticket gate"]
  },
  "Dashashwamedh Ghat": {
    title: "Dashashwamedh Ghat",
    subtitleEn: "Grand Ganga Aarti experience every evening",
    subtitleHi: "हर शाम भव्य गंगा आरती का अनुभव",
    image: "/images/ganga-aarti.png",
    english: "Dashashwamedh Ghat is the beating heart of Varanasi, and its name carries a grand mythological tale. According to scriptures, Lord Brahma performed a grand Ashwamedha (horse sacrifice) yajna here, sacrificing ten (Das) horses (Ashwa) to help Lord Shiva return to Kashi from exile. Another legend states that Brahma created the ghat to welcome Shiva. In the late 18th century, Queen Ashilyabai Holkar of Indore reconstructed the stone steps of the ghat. Every evening at sunset, Dashashwamedh Ghat transforms into a divine theater. A group of young Sanskrit scholars dressed in traditional dhotis performs the Ganga Aarti. They wave multi-tiered brass lamps, blow conch shells, and burn incense in a highly synchronized rhythmic pattern, while thousands of devotees watch from wooden boats floating on the river and from the crowded steps of the ghat.",
    hindi: "दशाश्वमेध घाट बनारस का सबसे जीवंत और ऐतिहासिक घाट है। इसका नाम एक बहुत ही पावन पौराणिक घटना से जुड़ा है। मान्यता है कि सृष्टि के रचयिता भगवान ब्रह्मा ने भगवान शिव को निर्वासन से वापस काशी बुलाने के लिए इस स्थान पर दस (दश) घोड़ों (अश्व) का भव्य यज्ञ (मेध) किया था, जिसके कारण इसका नाम दशाश्वमेध पड़ा। 1774 ईस्वी में इंदौर की महारानी अहिल्याबाई होल्कर ने इस घाट के पत्थर के घाटों का जीर्णोद्धार कराया था। हर शाम सूर्यास्त के समय, यहाँ दुनिया की सबसे भव्य गंगा आरती आयोजित की जाती है। पारंपरिक धोती और पीतांबर पहने युवा पुजारी मंत्रोच्चार और शंखनाद के बीच सात मंजिला पीतल के दीपकों से गंगा मैया की वंदना करते हैं, जिसे देखने के लिए देश-विदेश से हजारों श्रद्धालु नावों पर सवार होकर एकत्र होते हैं।",
    type: "Ghat",
    architecture: "Grand tiered ghat overlooking the main bend of the Ganges River with standard concrete performance pillars.",
    timings: "Open 24 hours (Aarti starts around 06:30 PM)",
    bestTimeEn: "Arrive by 05:30 PM to secure a good viewing spot on the boats or main steps.",
    dressCode: "Comfortable ethnic clothes are recommended.",
    photoRules: "Fully allowed. Best angles are captured from boats floating in the river.",
    prasadInfo: "Prasad packets with Ganga soil and dry fruits distributed by the organizers.",
    nearbySpots: ["Kashi Vishwanath Temple", "Manikarnika Ghat"],
    bestVendors: ["Ganga Seva Nidhi organizers desk"]
  },
  "BHU Campus": {
    title: "BHU Campus",
    subtitleEn: "Heritage & Knowledge Hub of Varanasi",
    subtitleHi: "वाराणसी का विरासत और ज्ञान केंद्र",
    image: "/images/ghats-night.png",
    english: "Established in 1916 by the great freedom fighter Pandit Madan Mohan Malaviya, Banaras Hindu University (BHU) is a living monument to modern Indian education. Malaviya Ji envisioned a university that combined modern scientific knowledge with ancient Indian values. He collected donations from kings and commoners alike to build the campus. Spanning over 1,300 acres, the university is designed in a perfect semi-circular layout, mimicking the crescent moon shape of Varanasi's river bank. The campus houses the Bharat Kala Bhavan museum, which has an invaluable collection of miniature paintings and archaeological relics. At the center of the campus stands the towering New Kashi Vishwanath Temple (VT), built by the Birla family. Made of white marble, its majestic temple tower rises to 252 feet, making it the tallest temple tower in the entire world, and a major spiritual center for students and tourists.",
    hindi: "बनारस हिंदू विश्वविद्यालय (बीएचयू) की स्थापना 1916 में महान स्वतंत्रता सेनानी पंडित मदन मोहन मालवीय द्वारा की गई थी। मालवीय जी एक ऐसे विश्वविद्यालय का निर्माण करना चाहते थे जो आधुनिक वैज्ञानिक शिक्षा के साथ प्राचीन भारतीय संस्कारों का मेल कराए। इसके निर्माण के लिए उन्होंने राजाओं से लेकर आम जनता तक से दान एकत्र किया था। 1300 एकड़ से अधिक क्षेत्रफल में फैला यह परिसर अर्ध-वृत्ताकार रूप में बना है, जो बनारस के अर्धचंद्राकार घाटों की आकृति को दर्शाता है। परिसर के बीचों-बीच स्थित नया विश्वनाथ मंदिर (बिरला मंदिर) अपनी भव्यता के लिए विख्यात है। सफेद संगमरमर से बने इस मंदिर का शिखर 252 फीट ऊंचा है, जो विश्व में किसी भी मंदिर का सबसे ऊंचा शिखर है।",
    type: "Heritage",
    architecture: "Indo-Gothic red brick academic structures set along sprawling green lawns and canopy roads.",
    timings: "05:00 AM - 09:00 PM (Temple hours: 06:00 AM - 12:00 PM, 04:00 PM - 08:30 PM)",
    bestTimeEn: "Late afternoon for cool breezes and museum exploration.",
    dressCode: "Casual respectful attire.",
    photoRules: "Allowed. Drone photography requires strict campus registrar authorizations.",
    prasadInfo: "Sweet peda offerings and hot milk available at the temple courtyard dairy counters.",
    nearbySpots: ["Sankat Mochan Temple", "Lanka Chowk Eats"],
    bestVendors: ["Bharat Kala Bhavan museum desk"]
  },
  "Kaal Bhairav Temple": {
    title: "Kaal Bhairav Temple",
    subtitleEn: "The ancient Kotwal (Guardian) of Kashi",
    subtitleHi: "काशी के प्राचीन कोतवाल (रक्षक)",
    image: "/images/kaal-bhairav.png",
    english: "Kaal Bhairav Temple is the seat of the guardian deity of Varanasi, known as the 'Kotwal' or police chief of Kashi. According to Shiva Purana, when Lord Brahma spoke arrogantly, Lord Shiva created Bhairav from his third eye to humiliate Brahma. Bhairav severed Brahma's fifth head, but the head stuck to his hand due to the sin of killing a Brahman. To expiate his sin, Bhairav roamed the universe as a beggar until he entered Kashi, where the head fell to the ground at a spot named Kapal Mochan. Shiva commanded Bhairav to stay in Kashi forever as its protector. It is widely believed that anyone living in or visiting Varanasi must visit Kaal Bhairav first to seek his permission. The temple's inner chamber houses a silver-faced deity draped in garlands, holding a trident, and flanked by his vehicle, the black dog. Devotees are given a black thread (Ganda) for protection against evil spirits.",
    hindi: "काल भैरव मंदिर काशी के मुख्य कोतवाल का निवास स्थान है। शिवपुराण के अनुसार, जब ब्रह्मा जी में अहंकार आ गया था, तब भगवान शिव ने अपने त्रिनेत्र से भैरव को उत्पन्न किया। भैरव ने ब्रह्मा जी के पांचवें सिर को काट दिया, लेकिन ब्रह्महत्या के पाप के कारण वह सिर उनके हाथ से चिपक गया। इस पाप से मुक्ति के लिए भैरव तीन लोकों में घूमे, और जैसे ही उन्होंने काशी की सीमा में प्रवेश किया, वह सिर उनके हाथ से छूटकर गिर गया (उस स्थान को कपाल मोचन तीर्थ कहा जाता है)। तब शिव जी ने उन्हें काशी का 'कोतवाल' नियुक्त कर दिया। मान्यता है कि बाबा विश्वनाथ के दर्शन से पहले काल भैरव की आज्ञा लेना अनिवार्य है, अन्यथा यात्रा अधूरी मानी जाती है।",
    type: "Temple",
    architecture: "Traditional medieval stone courtyard layout containing intricate wooden panel doors.",
    timings: "05:00 AM - 01:30 PM, 04:30 PM - 09:30 PM",
    bestTimeEn: "Mid-day around 11:30 AM before afternoon closure doors.",
    dressCode: "Traditional simple wear.",
    photoRules: "No camera allowed inside the inner altar room.",
    prasadInfo: "Spun sugar candy (Dana) and sacred black threads tied by priests inside the doorway.",
    nearbySpots: ["Visheshwarganj Markets", "Kachori Gali"],
    bestVendors: ["Temple priest trustees"]
  },
  "Manikarnika Ghat": {
    title: "Manikarnika Ghat",
    subtitleEn: "Sacred Cremation Ground for Eternal Salvation",
    subtitleHi: "अनंत मोक्ष के लिए पवित्र श्मशान घाट",
    image: "/images/manikarnika-ghat.png",
    english: "Manikarnika Ghat is the threshold of liberation (Moksha) in Hinduism. The name Manikarnika is derived from two words: Mani (jewel) and Karnika (earring). According to scripture, Lord Vishnu dug a pond (Chakra Pushkarini Kund) here with his Sudarshana Chakra for Lord Shiva and Goddess Parvati to bathe. During their bath, Goddess Parvati's golden earring fell into the well. Another legend says Lord Shiva's earring fell here while he was dancing in cosmic ecstasy. It is believed that Lord Shiva himself whispers the Taraka Mantra (prayer of liberation) into the ears of everyone cremated here. Manikarnika is a Mahashmashan (great cremation ground) where the funeral pyres have burned continuously for thousands of years without stopping for a single day. The ghat presents a profound spiritual message: that death is not an end, but a transition and the ultimate union of the soul with the divine.",
    hindi: "मणिकर्णिका घाट हिंदू धर्म में जीवन और मृत्यु के चक्र से मुक्ति (मोक्ष) का सबसे पवित्र द्वार माना जाता है। मणिकर्णिका नाम 'मणि' (आभूषण) और 'कर्णिका' (कान की बाली) से मिलकर बना है। पौराणिक कथा के अनुसार, भगवान विष्णु ने अपने सुदर्शन चक्र से यहाँ एक कुंड (चक्रपुष्करिणी कुंड) खोदा था, ताकि शिव-पार्वती स्नान कर सकें। स्नान के दौरान माता पार्वती के कान का आभूषण इस कुंड में गिर गया था। दूसरी मान्यता है कि ब्रह्मांडीय नृत्य के दौरान भगवान शिव के कान की बाली यहाँ गिरी थी। माना जाता है कि यहाँ दाह-संस्कार किए जाने वाले प्रत्येक व्यक्ति के कान में स्वयं महादेव 'तारक मंत्र' फूंकते हैं। यह एक ऐसा श्मशान है जहाँ चिता की अग्नि कभी शांत नहीं होती।",
    type: "Ghat",
    architecture: "Traditional stone platforms layered with stacks of logs, under an ancient temple watchtower.",
    timings: "Open 24 hours",
    bestTimeEn: "Quiet afternoon periods from boats to maintain solemn respect.",
    dressCode: "Decent quiet attire. Do not wear flash colors.",
    photoRules: "Strictly forbidden. Taking photographs of cremation ceremonies is a severe violation.",
    prasadInfo: "Special holy ash available near Chakra Pushkarini Kund shrines.",
    nearbySpots: ["Scindia Ghat", "Lalita Ghat Corridor entrance"],
    bestVendors: ["Ghat priests council"]
  },
  "Ramnagar Fort": {
    title: "Ramnagar Fort",
    subtitleEn: "18th-century Royal Fort on the Ganges",
    subtitleHi: "गंगा तट पर स्थित 18वीं शताब्दी का शाही किला",
    image: "/images/ramnagar-fort.png",
    english: "Ramnagar Fort stands as a majestic sentinel on the eastern bank of the Ganges River. Built in 1750 CE by the ruler Kashi Naresh Raja Balwant Singh, the fort is constructed out of cream-colored Chunar sandstone in a blend of Mughal and Rajput architectural styles. The fort houses the Saraswati Bhawan museum, which contains a spectacular collection of royal vintage cars, gold-plated palanquins, ivory carvings, and weapons used in medieval warfare. It also displays a rare astronomical clock constructed in 1852 by the royal court astronomer, which shows the time, date, phases of the moon, and astronomical configurations. The fort is highly famous for its annual Ramlila celebration, where the entire town of Ramnagar is turned into a natural theater set for a month-to-play the story of Ramayana under the patronage of the Kashi Naresh.",
    hindi: "रामनगर किला गंगा के पूर्वी तट पर तुलसी घाट के ठीक सामने स्थित एक भव्य शाही धरोहर है। इसका निर्माण 1750 ईस्वी में काशी नरेश राजा बलवंत सिंह द्वारा चुनार के बलुआ पत्थरों से कराया गया था, जो मुगल और राजपूत स्थापत्य शैली का अद्भुत संगम है। इस किले के भीतर एक शाही संग्रहालय (सरस्वती भवन) है, जिसमें प्राचीन हथियार, सोने की पालकी, हाथी दांत की नक्काशी और एक ऐतिहासिक खगोलीय घड़ी प्रदर्शित है, जिसे 1852 में बनाया गया था। यह घड़ी न केवल समय बताती है बल्कि तिथि, चंद्रमा की कलाएं और ग्रहों की स्थिति भी दिखाती है। दशहरा के दौरान यहाँ आयोजित होने वाली विश्व प्रसिद्ध रामलीला की परंपरा 200 से अधिक वर्षों से अनवरत चली आ रही है।",
    type: "Heritage",
    architecture: "High-walled fortress constructed out of yellow sandstone, overlooking the river Ganga.",
    timings: "10:00 AM - 05:00 PM",
    bestTimeEn: "Winter season mornings around 11 AM.",
    dressCode: "Comfortable walking wear.",
    photoRules: "Allowed outside the palace. Photos are banned inside the museum room.",
    prasadInfo: "Royal sweet peda sold at standard heritage counters near the gates.",
    nearbySpots: ["Ramnagar Ganga river crossing", "Lassi shops nearby"],
    bestVendors: ["Royal trust guards desk"]
  },
  "Swarved Mahamandir": {
    title: "Swarved Mahamandir",
    subtitleEn: "Grand Multistory Meditation Temple",
    subtitleHi: "भव्य बहुमंजिला ध्यान मंदिर",
    image: "/images/swarved-mahamandir.png",
    english: "Located in Umaraha, Varanasi, Swarved Mahamandir is a state-of-the-art meditation temple that serves as a modern spiritual wonder. The temple is named after the 'Swarved', a spiritual treatise written by Sadguru Sadafal Deo Ji Maharaj, the founder of Vihangam Yoga. The temple is a massive seven-story structure built entirely of white Makrana marble, adorned with intricate carvings of over 3,137 verses of the Swarved. The temple is designed with a seating capacity for over 20,000 people to meditate together. At its top, it features a majestic 125-petal lotus dome. The architecture seamlessly integrates ancient Indian heritage with brilliant modern eco-friendly technology, featuring extensive solar energy panels and surrounded by lush green gardens of medicinal herbs.",
    hindi: "उमराहा, वाराणसी में स्थित स्वर्वेद महामंदिर एक आध्यात्मिक चमत्कार है, जिसे दुनिया के सबसे बड़े ध्यान केंद्रों में गिना जाता है। इसका नाम विहंगम योग के प्रणेता सद्गुरु सदाफल देव जी महाराज द्वारा लिखित ग्रंथ 'स्वर्वेद' के नाम पर रखा गया है। यह सात मंजिला भव्य मंदिर पूरी तरह से मकराना के सफेद संगमरमर से बना है, जिसकी दीवारों पर स्वर्वेद के 3,137 से अधिक दोहे और श्लोक खूबसूरती से उकेरे गए हैं। इस मंदिर में एक साथ 20,000 से अधिक लोग बैठकर ध्यान लगा सकते हैं। इसके शीर्ष पर 125 पंखुड़ियों वाला कमल गुंबद बना है। यह मंदिर प्राचीन भारतीय स्थापत्य कला और आधुनिक सौर ऊर्जा तकनीक का एक बेहतरीन उदाहरण है।",
    type: "Temple",
    architecture: "Stunning 7-story marble structure with a massive lotus-shaped dome and modern glass elevator tubes.",
    timings: "06:00 AM - 07:00 PM",
    bestTimeEn: "08:00 AM or 05:00 PM for deep quiet meditation hours.",
    dressCode: "Clean comfortable clothes. White outfit preferred for meditation sessions.",
    photoRules: "Allowed on lawns. Mobile devices must remain silent inside halls.",
    prasadInfo: "Spiritual literature booklet and dried fruits at reception counters.",
    nearbySpots: ["Umaraha green belt", "Sarnath via Ring Road"],
    bestVendors: ["Swarved meditation trust volunteers"]
  },
  "Alaknanda Jetty": {
    title: "Alaknanda Jetty",
    subtitleEn: "Luxury Ganga Double-Decker Cruise Liner",
    subtitleHi: "गंगा नदी पर चलने वाला पहला लक्जरी डबल-डेकर क्रूज",
    image: "/images/alaknanda-jetty.jpg",
    english: "Alaknanda Jetty is the primary boarding point for the Alaknanda Cruise, Varanasi's first modern luxury double-decker cruise liner. Launched in 2018, this state-of-the-art vessel has revolutionized river tourism on the sacred Ganges. Spanning two floors, it features fully air-conditioned lower decks with large glass windows and an open-air upper observation deck that offers panoramic views of Varanasi's legendary ghats. The cruise route stretches from Assi Ghat all the way to Rajghat, covering all 84 historic ghats of Varanasi. It is most famous for its evening cruise, where passengers can witness the spectacular Ganga Aarti at Dashashwamedh Ghat from the serene vantage point of the river, accompanied by live cultural music and informative commentary about Kashi's history and heritage.",
    hindi: "अलकनंदा जेटी अलकनंदा क्रूज का मुख्य बोर्डिंग प्वाइंट है, जो वाराणसी की गंगा नदी में चलने वाला पहला आधुनिक लक्जरी डबल-डेकर क्रूज है। 2018 में शुरू हुए इस क्रूज ने पवित्र गंगा नदी के पर्यटन में एक नया अध्याय जोड़ा है। दो मंजिलों वाले इस जहाज में नीचे का डेक पूरी तरह से वातानुकूलित है जिसमें बड़ी शीशे की खिड़कियां लगी हैं, जबकि ऊपरी डेक खुला हुआ है जहाँ से बनारस के अर्धचंद्राकार घाटों का विहंगम दृश्य दिखाई देता है। यह क्रूज रविदास घाट से लेकर राजघाट तक की यात्रा कराता है, जिसमें बनारस के सभी 84 ऐतिहासिक घाटों को कवर किया जाता है। इसकी सबसे बड़ी विशेषता शाम की सवारी है, जहाँ यात्री दशाश्वमेध घाट की विश्व प्रसिद्ध गंगा आरती को बीच गंगा की धारा से देख सकते हैं, साथ ही लाइव संगीत और बनारस के इतिहास की कमेंट्री का आनंद भी ले सकते हैं।",
    type: "Boat",
    architecture: "State-of-the-art metal hull catamarans equipped with luxury passenger seats and glass views.",
    timings: "05:00 AM - 09:00 PM (Morning & Evening sessions)",
    bestTimeEn: "Evening trip starting around 05:30 PM for sunset golden hours.",
    dressCode: "Smart casuals.",
    photoRules: "Allowed. Excellent sunset landscape photographs can be clicked from open observation decks.",
    prasadInfo: "Local Banarasi sweets and refreshments served on-board during operations.",
    nearbySpots: ["Ravidas Ghat steps", "Assi Ghat"],
    bestVendors: ["Alaknanda River Cruise ticket portal"]
  },

  // Food delicacies
  "Tamatar Chaat": {
    title: "Tamatar Chaat",
    subtitleEn: "Varanasi's Legendary Street Food",
    subtitleHi: "वाराणसी का प्रसिद्ध स्ट्रीट फूड",
    image: "/images/tamatar-chaat.png",
    english: "Tamatar Chaat is a culinary legend exclusive to the streets of Banaras, born out of local creativity and spice blending. It is made by boiling potatoes and red tomatoes, then mashing them together on a massive iron griddle (tawa) with ginger, green chilies, coriander powder, garam masala, and a touch of red chili. The true magic lies in the finish - it is drenched in a sweet cumin-infused sugar syrup (jeera chashni) and hot ghee. Traditionally served piping hot in clay bowls (kulhad or dona), it offers a sweet, sour, spicy, and tangy taste that represents the vibrance of Banaras street food culture.",
    hindi: "टमाटर चाट बनारस की गलियों का एक ऐसा स्वाद है जो दुनिया में कहीं और नहीं मिल सकता। इसे उबले हुए आलू और ताजे लाल टमाटरों को बड़े लोहे के तवे पर अदरक, हरी मिर्च, गरम मसाला और अमचूर पाउडर के साथ मैश करके पकाया जाता है। इस चाट का मुख्य जादू अंत में होता, जब इसके ऊपर देसी घी और भुने जीरे की मीठी चाशनी (चाशनी का तड़का) डाली जाती है। इसे पारंपरिक रूप से मिट्टी के दोने में गर्मागर्म परोसा जाता है, जिसमें खट्टा, मीठा, तीखा और चटपटा स्वाद एक साथ मिलकर मुंह में स्वाद का धमाका करता है।",
    type: "Food",
    ingredients: ["Tomatoes", "Potatoes", "Ghee", "Jeera sugar syrup", "Ginger", "Coriander", "Local spices"],
    spiceLevel: 4,
    sweetnessLevel: 3,
    vegOption: "100% Vegetarian (No Onion, No Garlic option is widely available)",
    bestVendors: ["Kashi Chaat Bhandar (Godowlia)", "Deena Chaat Bhandar (Luxa)"],
    calories: "280 kcal per serving",
    priceRange: "₹40 - ₹60",
    popularityData: [60, 75, 85, 95, 90, 85]
  },
  "Malaiyyo": {
    title: "Malaiyyo",
    subtitleEn: "Winter's Ethereal Saffron Froth Sweet",
    subtitleHi: "सर्दियों की केसरिया ओस से बनी अनोखी मिठाई",
    image: "/images/malaiyoo.png",
    english: "Malaiyyo is a mysterious, cloud-like winter dessert found only in Varanasi. The preparation is a delicate, ancient art. Raw milk is boiled in large iron woks, mixed with saffron, and placed under the open night sky during peak winter. The milk absorbs the cold morning dew (shabnam) overnight. At dawn, artisans manually whisk the chilled milk using wooden churners for hours until it turns into a light, aerated foam. It is served in clay cups (kulhad), garnished with almonds, pistachios, and saffron. It melts instantly on the tongue, leaving a sweet, cardamom-infused aroma, representing the winter magic of Kashi.",
    hindi: "मलइयो बनारस की एक ऐसी रहस्यमयी और स्वादिष्ट मिठाई है जो केवल सर्दियों के दिनों में मिलती है। इसे बनाने की विधि एक प्राचीन कला है। दूध को उबालकर बड़े कड़ाहे में रखा जाता है, उसमें केसर मिलाया जाता है और रात भर ठंडी ओस (शबनम) को सोखने के लिए खुली छत पर छोड़ दिया जाता है। भोर में, कारीगर इस ठंडे दूध को मथनी से घंटों तक फेंटते हैं जब तक कि वह झागदार और बादलों की तरह हल्का न हो जाए। इसके बाद इसे कुल्हड़ में बादाम, पिस्ता और केसर की कतरन के साथ परोसा जाता है। यह मुंह में जाते ही पिघल जाता है।",
    type: "Food",
    ingredients: ["Full-fat Milk", "Saffron (Kesar)", "Cardamom", "Pistachios", "Almonds", "Sugar"],
    spiceLevel: 1,
    sweetnessLevel: 4,
    vegOption: "100% Vegetarian (Pure milk product)",
    bestVendors: ["Markandey Lassi & Malaiyyo (Chowk)", "Blue Lassi (Kachori Gali)"],
    calories: "180 kcal per cup",
    priceRange: "₹40 - ₹80",
    popularityData: [20, 10, 5, 80, 95, 99]
  },
  "Banarasi Lassi": {
    title: "Banarasi Lassi",
    subtitleEn: "Rich, Creamy Kulhad Lassi with Rabdi",
    subtitleHi: "रबड़ी और मलाईदार कुल्हड़ लस्सी",
    image: "/images/banarasi-lassi.png",
    english: "Banarasi Lassi is not just a beverage; it is a rich, creamy meal in itself. Unlike thin lassis, the Banarasi variant is hand-churned in wooden pots using thick, fresh yogurt and sugar. It is poured into large clay cups (kulhads), which absorb moisture and give the lassi a unique earthy aroma. The lassi is topped with a generous layer of fresh thick cream (malai), rich rabdi (reduced milk sweet), and a drizzle of rose water or saffron syrup, finished with grated pistachios and almonds. Legendary shops near the Vishwanath Gali have served this filling drink to pilgrims for over a century.",
    hindi: "बनारसी लस्सी सिर्फ एक पेय नहीं है, बल्कि यह अपने आप में एक संपूर्ण आहार है। इसे बनाने के लिए गाढ़े दही और चीनी को लकड़ी की मथनी से मिट्टी के बर्तनों में फेंटा जाता है। इसके बाद इसे लाल मिट्टी के कुल्हड़ में ढाला जाता है, जिससे इसमें सोंधी खुशबू आती है। इसके ऊपर ताजी मलाई की मोटी परत, लच्छेदार रबड़ी और गुलाब जल डाला जाता है, जिसे काजू-बादाम और पिस्ते की कतरन से सजाया जाता है। विश्वनाथ गली के पास स्थित प्रसिद्ध लस्सी की दुकानें दशकों से श्रद्धालुओं की थकान मिटा रही हैं।",
    type: "Food",
    ingredients: ["Thick Yogurt", "Sugar", "Rabdi", "Fresh Malai", "Rose syrup", "Cardamom", "Pistachios"],
    spiceLevel: 1,
    sweetnessLevel: 5,
    vegOption: "100% Vegetarian (Satvik option)",
    bestVendors: ["Blue Lassi Shop (Kachori Gali)", "Pahalwan Lassi (Lanka)"],
    calories: "340 kcal per kulhad",
    priceRange: "₹40 - ₹90",
    popularityData: [85, 90, 95, 95, 85, 80]
  },
  "Kachori Sabzi": {
    title: "Kachori Sabzi",
    subtitleEn: "Banaras's Signature Spicy Breakfast Combo",
    subtitleHi: "बनारस का पारंपरिक और तीखा नाश्ता",
    image: "/images/kachori-sabji.png",
    english: "Kachori Sabzi is the default breakfast that fuels Varanasi every single morning. The meal features two distinct types of kachoris: Badi Kachori (made of wheat flour and stuffed with dal paste) and Chhoti Kachori (crispy, round fried balls stuffed with spiced lentils). These are paired with a spicy, aromatic potato curry (sabzi) made with black chickpeas, ginger, and a special blend of local ground masalas. The heat of the spicy curry is traditionally balanced by eating hot, syrup-filled jalebis right after, creating the perfect sweet-and-spicy breakfast start to a Banarasi day.",
    hindi: "कचौड़ी सब्जी बनारस का वह पारंपरिक नाश्ता है जिससे हर बनारसी के दिन की शुरुआत होती है। इसमें दो तरह की कचौड़ियां होती हैं: बड़ी कचौड़ी (गेहूं के आटे से बनी, उड़द दाल भरी) और छोटी कचौड़ी (कुरकुरी, तीखी दाल भरी)। इन्हें काले चने और आलू की बेहद तीखी सब्जी के साथ परोसा जाता है, जिसमें लेखक लहसुन-प्याज का उपयोग नहीं होता बल्कि मसालों का एक अनूठा स्वाद होता है। इस तीखे नाश्ते को संतुलित करने के लिए साथ में गरमागरम जलेबियां खाने की परंपरा है।",
    type: "Food",
    ingredients: ["Wheat flour", "Urad Dal paste", "Potatoes", "Black chickpeas", "Pure Ghee", "Asafoetida (Hing)", "Spices"],
    spiceLevel: 5,
    sweetnessLevel: 1,
    vegOption: "100% Satvik Veg (No Garlic, No Onion used in traditional preparation)",
    bestVendors: ["Ram Bhandar (Chowk)", "Chachi Ki Kachori (Lanka)"],
    calories: "420 kcal per plate",
    priceRange: "₹30 - ₹50",
    popularityData: [90, 95, 85, 80, 80, 85]
  },
  "Rabri Jalebi": {
    title: "Rabri Jalebi",
    subtitleEn: "Timeless Sweet Combination",
    subtitleHi: "रबड़ी और जलेबी का पारंपरिक मीठा संगम",
    image: "/images/jalebi-imarti.png",
    english: "Rabri Jalebi is Varanasi's most beloved dessert pairing, representing a perfect union of temperatures, textures, and tastes. Freshly fermented batter is piped into hot oil in circular loops to create thin, crispy jalebis, which are then soaked in warm cardamom sugar syrup. They are served alongside cold, slow-cooked, condensed milk rabri, which is reduced for hours in large woks until thick and creamy. The contrast of the hot, crunchy, syrup-filled jalebi with the cold, smooth, velvety rabri creates an absolute culinary masterpiece.",
    hindi: "रबड़ी जलेबी बनारस का सबसे लोकप्रिय मीठा व्यंजन है, जो स्वाद, तापमान और बनावट का एक बेजोड़ मेल है। ताजी तली हुई कुरकुरी जलेबियों को चाशनी में डुबोकर सीधे कढ़ाई से निकाला जाता है और गाढ़ी, मलाईदार रबड़ी के साथ परोसा जाता है। गर्म, खस्ता जलेबी के अंदर भरी मीठी चाशनी और ठंडी, गाढ़ी रबड़ी का मलाईदार स्वाद जब एक साथ मुंह में घुलता है, तो वह स्वाद का एक अद्भुत अनुभव प्रदान करता है।",
    type: "Food",
    ingredients: ["Maida flour", "Curd", "Ghee", "Milk cream", "Sugar", "Saffron", "Pistachio flakes"],
    spiceLevel: 1,
    sweetnessLevel: 5,
    vegOption: "100% Vegetarian (Pure Ghee base)",
    bestVendors: ["Ksheer Sagar (Rathyatra)", "Chowk Street Confectioners"],
    calories: "380 kcal per serving",
    priceRange: "₹50 - ₹90",
    popularityData: [80, 85, 90, 95, 90, 90]
  },
  "Banarasi Paan": {
    title: "Banarasi Paan",
    subtitleEn: "A Tradition of Taste and Refreshment",
    subtitleHi: "स्वाद और आतिथ्य की अनूठी बनारसी परंपरा",
    image: "/images/banarasi-paan.png",
    english: "Immortalized in Indian cinema and folklore, Banarasi Paan is a symbol of hospitality and refinement. The leaf used is the delicate 'Magahi' leaf, which is incredibly soft and melts in the mouth. Preparing a Banarasi Paan is an art form: the betel leaf is coated with slaked lime (chuna) and catechu (kattha), then stuffed with a mixture of gulkand (rose petal jam), fennel seeds, cardamom, grated coconut, and other sweet aromatic spices. Paan is chewed slowly, acting as a digestive and mouth freshener, and in Varanasi, sharing a paan is a traditional sign of respect, welcome, and cultural heritage.",
    hindi: "बनारसी पान भारतीय संस्कृति और लोकगीतों का एक अभिन्न हिस्सा है। इसके लिए विशेष 'मगही' पान के पत्ते का उपयोग किया जाता है, जो मुंह में जाते ही घुल जाता है। पान लगाने की कला बनारस में एक विरासत है, जहाँ पत्ते पर चूना, कत्था लगाकर उसमें गुलकंद, सौंफ, इलायची, गरी का बुरादा और मीठी सुपारी भरी जाती है। भोजन के बाद पान खाना न केवल पाचन क्रिया को सुगम बनाता है, बल्कि बनारस के लोगों के लिए यह बातचीत की शुरुआत करने और मेहमानों का आदर-सत्कार करने का एक पारंपरिक तरीका है।",
    type: "Food",
    ingredients: ["Magahi Betel leaf", "Kattha paste", "Slaked Lime", "Gulkand", "Sweet betelnut (Supari)", "Fennel seeds", "Mouth freshener spices"],
    spiceLevel: 1,
    sweetnessLevel: 4,
    vegOption: "100% Vegetarian & Digestant",
    bestVendors: ["Keshav Tambul (Lanka)", "Rajendra Chaurasia Paan (Godaulia)"],
    calories: "60 kcal per leaf",
    priceRange: "₹20 - ₹50",
    popularityData: [95, 98, 99, 99, 95, 95]
  },
  "Kulfi Falooda": {
    title: "Kulfi Falooda",
    subtitleEn: "Creamy Frozen Saffron Rabri with Noodles",
    subtitleHi: "केसरिया मलाई कुल्फी और फालूदा सेव",
    image: "/images/kulfi-falooda.png",
    english: "Kulfi Falooda is a highly popular cooling dessert enjoyed along the ghats and busy markets of Varanasi. The kulfi is prepared by boiling full-fat milk slowly until it reduces to a rich, caramelised solid, flavored with saffron, cardamom, and chopped nuts before freezing. It is served sliced on a plate or in a bowl, topped with silky, translucent cornstarch noodles (falooda) and a generous drizzle of sweet rose syrup or khus syrup. The rich, dense, slow-melting saffron kulfi matches perfectly with the cooling, soft texture of the falooda noodles.",
    hindi: "कुल्फी फालूदा बनारस के घाटों और बाजारों में खाया जाने वाला एक अत्यंत लोकप्रिय और ठंडा व्यंजन है। कुल्फी को दूध को गाढ़ा करके, उसमें केसर, इलायची और सूखे मेवे मिलाकर जमाया जाता है। इसे प्लेट में काटकर ठंडी फालूदा सेव और गुलाब के सिरप (रूह अफ़ज़ा) के साथ परोसा जाता है, जो गर्मियों में ठंडक और अनोखा स्वाद प्रदान करता है।",
    type: "Food",
    ingredients: ["Reduced milk solids (Rabdi)", "Saffron", "Rose syrup", "Cornstarch falooda noodles", "Almonds", "Cashews"],
    spiceLevel: 1,
    sweetnessLevel: 4,
    vegOption: "100% Vegetarian",
    bestVendors: ["Chowk sweets corner", "Rathyatra sweet plaza"],
    calories: "290 kcal per bowl",
    priceRange: "₹45 - ₹80",
    popularityData: [70, 80, 90, 90, 75, 70]
  },
  "Thandai": {
    title: "Thandai",
    subtitleEn: "Festival Drink of Kashi with Almonds and Spices",
    subtitleHi: "केसर, बादाम और मसालों से बना बनारसी पेय",
    image: "/images/thandai.png",
    english: "Thandai is the quintessential celebratory beverage of Kashi, deeply linked to the worship of Lord Shiva, especially during Maha Shivratri and Holi. It is a refreshing, cooling drink made from a paste of almonds, fennel seeds, watermelon seeds, rose petals, black pepper, cardamom, and saffron, blended into chilled milk. In Varanasi, traditional thandai houses serve this rich beverage in clay cups (kulhads), garnished with thick rabdi and saffron. Devotees also enjoy a special version mixed with fresh herb paste (bhang) as a sacred offering to the deity.",
    hindi: "ठंडाई काशी का एक पारंपरिक और पवित्र पेय है, जो विशेष रूप से महाशिवरात्रि और होली के दौरान भगवान शिव की पूजा और उत्सव से गहराई से जुड़ा हुआ है। इसे बादाम, सौंफ, खरबूजे के बीज, सूखी गुलाब की पंखुड़ियों, काली मिर्च, इलायची और केसर को पीसकर गाढ़े ठंडे दूध में मिलाकर बनाया जाता है। बनारस में इसे कुल्हड़ में रबड़ी और केसर से सजाकर परोसा जाता है।",
    type: "Food",
    ingredients: ["Chilled Milk", "Almond paste", "Fennel seeds", "Watermelon seeds", "Rose petals", "Black pepper", "Saffron"],
    spiceLevel: 2,
    sweetnessLevel: 4,
    vegOption: "100% Vegetarian (Special herbal variants are prepared during Shivratri)",
    bestVendors: ["Mishrambu Thandai (Godowlia)", "Pathak Thandai (Chowk)"],
    calories: "260 kcal per kulhad",
    priceRange: "₹45 - ₹90",
    popularityData: [50, 60, 99, 99, 70, 60]
  },
  "Malpua Rabri": {
    title: "Malpua Rabri",
    subtitleEn: "Crispy Sweet Pancakes with Velvety Reduced Milk",
    subtitleHi: "रसीले मालपुए और मलाईदार रबड़ी का मेल",
    image: "/images/malpua-rabri.png",
    english: "Malpua Rabri is a royal sweet combination prepared during festivals and auspicious occasions in Kashi. Malpuas are sweet, cardamom-scented pancakes made from a batter of flour, milk, and mashed bananas, deep-fried in pure ghee until the edges turn golden and crispy. Once fried, they are instantly soaked in warm sugar syrup. These warm, juicy pancakes are served fresh with a topping of cold, creamy, slow-cooked Rabri, garnished with sliced pistachios and almonds, creating an unforgettable sweet experience.",
    hindi: "मालपुआ रबड़ी बनारस में त्योहारों और शुभ अवसरों पर बनाई जाने वाली एक बेहद स्वादिष्ट मिठाई है। मालपुआ मैदा, सूजी और दूध के घोल से बने मीठे पैनकेक होते हैं जिन्हें देसी घी में सुनहरा होने तक तला जाता है और फिर चाशनी में डुबोया जाता है। इसे ठंडी, गाढ़ी और मलाईदार रबड़ी के साथ परोसा जाता है, जिसके ऊपर पिस्ता और बादाम की कतरन सजी होती है।",
    type: "Food",
    ingredients: ["Wheat flour", "Mashed bananas", "Pure Ghee", "Sugar syrup", "Milk cream", "Pistachios", "Almonds"],
    spiceLevel: 1,
    sweetnessLevel: 5,
    vegOption: "100% Vegetarian",
    bestVendors: ["Rajbandhu Sweets (Chowk)", "Ksheer Sagar counters"],
    calories: "450 kcal per serving",
    priceRange: "₹60 - ₹100",
    popularityData: [60, 70, 85, 95, 80, 70]
  },
  "Rabdi": {
    title: "Rabdi",
    subtitleEn: "Rich Slow-Cooked Condensed Milk Dessert",
    subtitleHi: "घंटों धीमी आंच पर पककर तैयार गाढ़ी रबड़ी",
    image: "/images/rabdi.png",
    english: "Rabdi is a sweet, condensed-milk dessert that forms the base of many traditional Banarasi sweets. It is prepared by heating full-cream milk in a massive shallow iron pan (kadai). As the milk boils, a layer of cream forms on top, which the artisan continuously pushes to the sides of the pan. This process is repeated for hours until only a small fraction of thick liquid remains, which is sweetened with sugar, flavored with cardamom, and mixed with the collected layers of cream, resulting in a rich, textured, multi-layered dessert.",
    hindi: "रबड़ी दूध से बनने वाला एक पारंपरिक व्यंजन है जो बनारस की कई प्रसिद्ध मिठाइयों का आधार है। इसे बनाने के लिए दूध को लोहे की कड़ाही में तब तक उबाला जाता है जब तक कि वह गाढ़ा न हो जाए। उबलते दूध के ऊपर आने वाली मलाई की परतों को कड़ाही के किनारों पर इकट्ठा किया जाता है। अंत में, इसमें थोड़ी चीनी और इलायची मिलाकर मलाईदार लच्छों को वापस मिला दिया जाता है।",
    type: "Food",
    ingredients: ["Full-cream Milk", "Sugar", "Cardamom powder", "Pistachios", "Almond flakes"],
    spiceLevel: 1,
    sweetnessLevel: 4,
    vegOption: "100% Vegetarian",
    bestVendors: ["Chowk Confectioners market", "Godaulia local dairies"],
    calories: "220 kcal per cup",
    priceRange: "₹40 - ₹80",
    popularityData: [75, 80, 85, 90, 80, 80]
  }
};
